### PR TITLE
Voting

### PR DESCRIPTION
**Pull request by sofiaclara93**
I used ajax to create a vote, the voting button eventually needs to be moved to the left of the question. I also made it so the user can only vote once by making a uniqueness validation, but i didn't create an error for if they try to vote more than once, it simply just doesn't work for the user.

### CODE REVIEW

**Comment by evanrenaud** [comment]
does this work without JavaScript? Or only with AJAX? I'm not sure how to pull it and test it myself

edit: found out how to test it, standby

**Comment by sofiaclara93** [comment]
Yeah it doesn't work without it I just have to make it redirect

**Comment by evanrenaud** [comment]
alright. this looks fine. we may eventually want to add logic so the vote can be changed from +1 to -1 or vice versa, or back to 0 (similar to reddit's system) but it looks good for now.

Although for some reason I can no longer view questions for our custom submitted questions

**Comment by evanrenaud** [comment]
Yeah, you had deleted the @best_answer line in the questions controller, which causes a sinatra error

**Comment by sofiaclara93** [comment]
what line I can add it back

**Comment by evanrenaud** [comment]
I just edited it. Looks good to merge

**Pull request merged**
